---
title: "Activity Correctness Prediction"
author: "Tomas Gogorza"
date: "27 de noviembre de 2015"
output: html_document
---

#Load and Understand Data

```{r}
library(caret)
library(parallel)
library(doSNOW)
#library(norm)
library(dplyr)
```

#Load and Clean Data Set

```{r cache=TRUE}
trainData <- read.csv("pml-training.csv")
testData <- read.csv("pml-testing.csv")

#Remove fields with more than 19000 NAs and empty data
classe <- trainData$classe
trainData <- select(trainData,-classe)
trainData <- trainData[ , apply(trainData,2,function(x){ sum(is.na(x)) < 19000 })]
trainData <- trainData[ , apply(trainData,2,function(x){ !("#DIV/0!" %in% x) })]
trainData <- trainData[ , -c(2:6)]

testData <- select(testData,-problem_id) 
testData <- testData[ , apply(testData,2,function(x){ sum(is.na(x)) != 20 })]
testData <- testData[ , apply(testData,2,function(x){ !("#DIV/0!" %in% x) })]
testData <- testData[ , -c(2:6)]

str(trainData)
str(testData)
```

#Predictive Model

```{r, echo=FALSE}

preProcValues <- preProcess(trainData, method = c("center", "scale"))
#preProcTest <- preProcess(testData, method = c("center", "scale"))

trainData <- predict(preProcValues, trainData)
testData <- predict(preProcValues, testData)

#Create Cross Validation set
trainInd <- createDataPartition(classe, p = 0.8, list = FALSE)
validationData <- trainData[-trainInd,]
validationLabels <- classe[-trainInd]
trainData <- trainData[trainInd,]
trainLabels <- classe[trainInd]

#Dimensionality Reduction


#Parallel Training
cl <- makeCluster(4, type = "SOCK")
registerDoSNOW(cl)

fitControl <- trainControl(method="repeatedcv",  #method = "repeatedcv",
                           #number = 5)
                           #number = 10,
                           repeats = 5)

clusterSetupRNG(cl, seed=rep(12345,6))
a <- clusterCall(cl, runif, 10000)

gbmFit <- train(x=trainData, y=trainLabels,
                 method = "gbm",
                 #trControl = fitControl,
                 preProcess=c("pca"),
                 verbose = FALSE)

rfFit <- train(x=trainData, y=trainLabels,
                 method = "rf",
                 #trControl = fitControl,
                 preProcess=c("pca"),
                 verbose = FALSE)

adaFit <- train(x=trainData, y=trainLabels,
                 method = "ada",
                 #trControl = fitControl,
                 preProcess=c("pca"),
                 verbose = FALSE)

nbFit <- train(x=trainData, y=trainLabels,
                 method = "nb",
                 #trControl = fitControl,
                 preProcess=c("pca"),
                 verbose = FALSE)

stopCluster(cl)
```


#Prediction
```{r}
save(rfFit,file = "rfFit.RData")
save(rfFit,file = "rfFitPCA.RData")
save(gbmFit,file = "gbmFit.RData")
save(adaFit,file = "adaFit.RData")
save(nbFit,file = "nbFit.RData")

pred <- predict(gbmFit,newdata = validationData)
confusionMatrix(pred,validationLabels)

predrf <- predict(rfFit,newdata = validationData)
confusionMatrix(predrf,validationLabels)

predada <- predict(adaFit,newdata = validationData)
confusionMatrix(predada,validationLabels)

prednb <- predict(nbFit,newdata = validationData)
confusionMatrix(prednb,validationLabels)

predict(gbmFit, newdata = testData)
predict(rfFit, newdata = testData)
predict(nbFit, newdata = testData)

actualLabels <- c("","A","","A","A","E","D","","A","A","","","B","A","E","","A","B","","B")

```

```{r cache=TRUE}
pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}

```

```{r}
pml_write_files(predict(nbFit,newdata = testData))
```